name: Tjoin
main: Tjoin.Tjoin
default-permission: OP
version: 0.2
commands:
   Tjoin:
       description: \u63d2\u4ef6\u91cd\u8bfb
       usage: \u4f7f\u7528/<command> reload
       permission: Tjoin
       permission-message: \u4f60\u6ca1\u6709\u6743\u9650\u4f7f\u7528\u8fd9\u4e2a\u6307\u4ee4